database:
  driver: "mysql"
  database: "vote_db"
  host: "localhost"
  port: "3306"
  username: "root"
  password: "1234"
api:
  enable: true
  port: "8090"
nodes:
  - host: "127.0.0.1"
    httpPort: "8545"
    wsPort: "8546"